# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame_bundle.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'frame_bundle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66rame_bundle.proto\"\xcc\x01\n\x0b\x46rameBundle\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x05\x12\x16\n\x0ergb_image_data\x18\x02 \x01(\x0c\x12\x12\n\ndepth_data\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65pth_width\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x65pth_height\x18\x05 \x01(\x05\x12\x13\n\x0bimage_width\x18\x06 \x01(\x05\x12\x14\n\x0cimage_height\x18\x07 \x01(\x05\x12\x11\n\ttransform\x18\x08 \x03(\x02\x12\x12\n\nintrinsics\x18\t \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_bundle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEBUNDLE']._serialized_start=23
  _globals['_FRAMEBUNDLE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
